default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3




# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: joshedb

test:
  <<: *default
  database: app_name_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>